### PR TITLE
resource_tailnet_key: handle 404 and discard invalid keys

### LINKED ISSUE #144: The `tailscale_tailnet_key` resource should handle expired keys
**Describe the bug**
A few months after generating a few `tailscale_tailnet_key` resources in my terraform code, those keys expired in tailscale control and were subsequently deleted by the api. Now when I run my Terraform again after the keys have expired, the provider fails to fetch these keys and blocks my Terraform deployment.

**To Reproduce**
Steps to reproduce the behaviour:
1. Terraform apply a `tailscale_tailnet_key` with `reusable = true`
2. Wait for the key to expire (or revoke it so you don't have to wait around)
3. Terraform plan/apply using same configuration
4. Fail to fetch key with 404
```
Error: Failed to fetch key

  with tailscale_tailnet_key.reusable,
  on my_keys.tf line 1, in resource "tailscale_tailnet_key" "reusable":
   1: resource "tailscale_tailnet_key" "reusable" {

404 page not found (404)
```

**Expected behaviour**
The provider detects an expired key by evaluating that the expire time/date in state is less than the current time/date and that the resource is a 404 response from the api, removes the resource from state, then a plan is calculated to recreate the resource to ensure the desired end state.

**Desktop (please complete the following information):**
 - OS: linux
 - Terraform Version 1.1.9
 - Provider Version 0.12.2

**Additional context**
This is similar to an issue brought up in #59 where keys would vanish from the API, except due to `reusable = false`

### PR DESCRIPTION
**Pull request by clstokes**
**What this PR does / why we need it**:

1. Changes the handling of 404 errors on Read / `terraform refresh` operations to treat all 404 errors as a deleted key. Previously only one-time keys (e.g _not_ reusable) were treated as deleted and a 404 would fail the terraform operation with an error.
2. Removes tailnet key from state during Read operation if `invalid` key property is `true`.

**Which issue this PR fixes**: 

Fixes #144

**Special notes for your reviewer**:

~Any concerns with using the time of the machine that is running Terraform to compare with `expires_at` returned by the Tailscale API?~

### CODE REVIEW

**Comment by clstokes** [comment]
Local testing...

#### main.tf
```hcl
variable "expiry" {
    default = 30
}

resource "tailscale_tailnet_key" "instance" {
  expiry   = var.expiry
  reusable = false
  tags     = ["tag:demo-exit-node"]
}

output "key_id" {
    value = tailscale_tailnet_key.instance.id
}

output "expiry" {
    value = var.expiry
}
```

#### test steps / output
```
# TF_CLI_CONFIG_FILE=.terraformrc terraform apply -auto-approve
╷
│ Warning: Provider development overrides are in effect
│ 
│ The following provider development overrides are set in the CLI configuration:
│  - tailscale/tailscale in /Users/cameron/.terraform.d/plugins/github.com/tailscale/tailscale/0.1/darwin_arm64
│ 
│ The behavior may therefore not match any released version of the provider and applying changes may cause the state to become incompatible with published releases.
╵

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # tailscale_tailnet_key.instance will be created
  + resource "tailscale_tailnet_key" "instance" {
      + created_at = (known after apply)
      + expires_at = (known after apply)
      + expiry     = 30
      + id         = (known after apply)
      + key        = (sensitive value)
      + reusable   = false
      + tags       = [
          + "tag:demo-exit-node",
        ]
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  ~ key_id = "kxqFHN3CNTRL" -> (known after apply)
tailscale_tailnet_key.instance: Creating...
tailscale_tailnet_key.instance: Creation complete after 0s [id=key1]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Outputs:

expiry = 30
key_id = "key1"
#  
#  
# 
# TF_CLI_CONFIG_FILE=.terraformrc terraform refresh            
tailscale_tailnet_key.instance: Refreshing state... [id=key1]

Outputs:

expiry = 30
key_id = "key1"
#  
#  
# 
# TF_CLI_CONFIG_FILE=.terraformrc terraform refresh
tailscale_tailnet_key.instance: Refreshing state... [id=key1]

Outputs:

expiry = 30
key_id = "key1"
#  
#  
# 
# TF_CLI_CONFIG_FILE=.terraformrc terraform apply -auto-approve
╷
│ Warning: Provider development overrides are in effect
│ 
│ The following provider development overrides are set in the CLI configuration:
│  - tailscale/tailscale in /Users/cameron/.terraform.d/plugins/github.com/tailscale/tailscale/0.1/darwin_arm64
│ 
│ The behavior may therefore not match any released version of the provider and applying changes may cause the state to become incompatible with published releases.
╵
tailscale_tailnet_key.instance: Refreshing state... [id=key1]

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

expiry = 30
key_id = "key1"
#  
#  
# 
# sleep $(terraform output expiry)                 
#  
#  
# 
# TF_CLI_CONFIG_FILE=.terraformrc terraform apply -auto-approve
╷
│ Warning: Provider development overrides are in effect
│ 
│ The following provider development overrides are set in the CLI configuration:
│  - tailscale/tailscale in /Users/cameron/.terraform.d/plugins/github.com/tailscale/tailscale/0.1/darwin_arm64
│ 
│ The behavior may therefore not match any released version of the provider and applying changes may cause the state to become incompatible with published
│ releases.
╵
tailscale_tailnet_key.instance: Refreshing state... [id=key1]

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply" which may have affected this plan:

  # tailscale_tailnet_key.instance has been deleted
  - resource "tailscale_tailnet_key" "instance" {
      - id         = "key1" -> null
        tags       = [
            "tag:demo-exit-node",
        ]
        # (6 unchanged attributes hidden)
    }


Unless you have made equivalent changes to your configuration, or ignored the relevant attributes using ignore_changes, the following plan may include actions to
undo or respond to these changes.

──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # tailscale_tailnet_key.instance will be created
  + resource "tailscale_tailnet_key" "instance" {
      + created_at = (known after apply)
      + expires_at = (known after apply)
      + expiry     = 30
      + id         = (known after apply)
      + key        = (sensitive value)
      + reusable   = false
      + tags       = [
          + "tag:demo-exit-node",
        ]
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  ~ key_id = "key1" -> (known after apply)
tailscale_tailnet_key.instance: Creating...
tailscale_tailnet_key.instance: Creation complete after 0s [id=key2]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Outputs:

expiry = 30
key_id = "key2"
#  
#  
# 
# TF_CLI_CONFIG_FILE=.terraformrc terraform destroy -auto-approve
╷
│ Warning: Provider development overrides are in effect
│ 
│ The following provider development overrides are set in the CLI configuration:
│  - tailscale/tailscale in /Users/cameron/.terraform.d/plugins/github.com/tailscale/tailscale/0.1/darwin_arm64
│ 
│ The behavior may therefore not match any released version of the provider and applying changes may cause the state to become incompatible with published
│ releases.
╵
tailscale_tailnet_key.instance: Refreshing state... [id=key2]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  - destroy

Terraform will perform the following actions:

  # tailscale_tailnet_key.instance will be destroyed
  - resource "tailscale_tailnet_key" "instance" {
      - created_at = "2023-09-12T17:49:38Z" -> null
      - ephemeral  = false -> null
      - expires_at = "2023-09-12T17:50:08Z" -> null
      - expiry     = 30 -> null
      - id         = "key2" -> null
      - key        = (sensitive value) -> null
      - reusable   = false -> null
      - tags       = [
          - "tag:demo-exit-node",
        ] -> null
    }

Plan: 0 to add, 0 to change, 1 to destroy.

Changes to Outputs:
  - expiry = 30 -> null
  - key_id = "key2" -> null
tailscale_tailnet_key.instance: Destroying... [id=key2]
tailscale_tailnet_key.instance: Destruction complete after 2s

Destroy complete! Resources: 1 destroyed.
# 
```

File: tailscale/resource_tailnet_key.go [hunk 1]
```diff
@@ -167,7 +165,11 @@ func resourceTailnetKeyRead(ctx context.Context, d *schema.ResourceData, m inter
 		return diagnosticsError(err, "Failed to set created_at")
 	}
 
-	if err = d.Set("expires_at", key.Expires.Format(time.RFC3339)); err != nil {
+	if key.Expires.Before(time.Now().UTC()) {
```
Comment (knyar) [inline tailscale/resource_tailnet_key.go:168]: As you pointed out, this seems a bit risky, since we can't guarantee if the client's local time is in sync, so we might accidentally be deleting non-expired keys from Terraform state.

A slightly better way to handle this might be to compare `expires` field with the `date` HTTP response header, but it's not trivial to implement since the response headers are not currently exposed to the provider.

Or perhaps we could explicitly mark keys as expired in the response? Or not return expired keys at all?

**Comment by clstokes** [comment]
After internal discussion we're going to go a slightly different direction here that will require changes to the Tailscale API and https://github.com/tailscale/tailscale-client-go. I made this PR a draft and will come back to this once the upstream change are ready.

**Review by knyar — APPROVED** [review]
I've just made a new release that you can use here: https://github.com/tailscale/tailscale-client-go/releases/tag/v1.13.0
